name: Build And Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-container.yaml"
      - "Dockerfile"
  pull_request:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: web/winning11
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Determine the Image Tag
      - name: Set Image Tag
        id: tag
        run: |
          if [[ "${{ github.ref }}" == refs/heads/* ]]; then
            echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Build Docker Image
        run: |
          image_name=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          docker build -t "$image_name:latest" .

      # Push the Docker image to GHCR
      - name: Build and Push Docker Image
        run: |
          image_name=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          docker build . -t "$image_name:${{ env.tag }}" --push